JobBaMaWebApp/Models/JobPosting.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace JobBaMaWebApp.Models
{
    public class JobPosting
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Company { get; set; }

        
        public string Location { get; set; }

        public DateTime PostedDate { get; set; } = DateTime.UtcNow;

        public bool IsApproved { get; set; }

        [Required]
        public string UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        public IdentityUser User { get; set; }
    }
}

JobBaMaWebApp/ViewModels/JobPostingViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace JobBaMaWebApp.ViewModels
{
    public class JobPostingViewModel
    {
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Company { get; set; }
        [Required]
        public string Location { get; set; }
    }
}

JobBaMaWebApp/Controllers/JobPostingsController.cs
using JobBaMaWebApp.Constants;
using JobBaMaWebApp.Models;
using JobBaMaWebApp.Repositories;
using JobBaMaWebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace JobBaMaWebApp.Controllers
{
    [Authorize]
    public class JobPostingsController : Controller
    {
        private readonly IRepository<JobPosting> _repository;
        private readonly UserManager<IdentityUser> _userManager;

        public JobPostingsController(
            IRepository<JobPosting> repository,
            UserManager<IdentityUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var jobPostings = await _repository.GetAllAsync();

            if (User.IsInRole(Roles.Employer))
            {
                var userId = _userManager.GetUserId(User);
                var filteredJobPostings = jobPostings.Where(x => x.UserId == userId);
                return View(filteredJobPostings);
            }
            return View(jobPostings);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Employer")]
        public async Task<IActionResult> Create(JobPostingViewModel jobPostingViewModel)
        {
            if (ModelState.IsValid)
            {
                var jobPosting = new JobPosting
                {
                    Title = jobPostingViewModel.Title,
                    Description = jobPostingViewModel.Description,
                    Company = jobPostingViewModel.Company,
                    Location = jobPostingViewModel.Location,
                    UserId = _userManager.GetUserId(User)
                };
                await _repository.AddAsync(jobPosting);

                return RedirectToAction(nameof(Index));
            }
            return View(jobPostingViewModel);
        }

        [HttpDelete]

        public async Task<IActionResult> Delete(int id)
        {
            var jobPosting =  await _repository.GetByIdAsync(id);
            var userId = _userManager.GetUserId(User);

            if (jobPosting == null)
            {
                return NotFound();
            }

            if (User.IsInRole(Roles.Admin) == false && jobPosting.UserId != userId)
            {
                return Forbid();
            }
            await _repository.DeleteAsync(id);

            return Ok();
        }
    }
}

JobBaMaWebApp/Views/JobPostings/Create.cshtml
@model JobBaMaWebApp.ViewModels.JobPostingViewModel

@{
	Layout = "_Layout";
	ViewData["Title"] = "ساخت آگهی";
}

<h1>ساخت آگهی جدید</h1>

<form method="post" action="Create">

	<div class="mb-3">
		<label asp-for="Title" class="form-label">عنوان آگهی</label>
		<input type="text" asp-for="Title" class="form-control" />
		<span asp-validation-for="Title" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="Description" class="form-label">متن آگهی</label>
		<textarea type="text" asp-for="Description" class="form-control"></textarea>
		<span asp-validation-for="Description" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="Company" class="form-label">نام شرکت</label>
		<input type="text" asp-for="Company" class="form-control" />
		<span asp-validation-for="Company" class="text-danger"></span>
	</div>

	<div class="mb-3">
		<label asp-for="Location" class="form-label">مکان شرکت</label>
		<input type="text" asp-for="Location" class="form-control" />
		<span asp-validation-for="Location" class="text-danger"></span>
	</div>

	<button type="submit" class="btn btn-primary">ثبت</button>
</form>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

JobBaMaWebApp/Views/JobPostings/Index.cshtml
@using JobBaMaWebApp.Constants
@model IEnumerable<JobPosting>

@{
	Layout = "_Layout";
	ViewData["Title"] = "جا با ما";
}


<h1>مشاغل</h1>

<div class="list-group">

	@foreach (var jobPosting in Model)
	{
		<div class="list-group-item" id="jobPosting-@jobPosting.Id">
			<h3>@jobPosting.Title</h3>
			<p>@jobPosting.Description</p>
			<p><strong>شرکت : </strong>@jobPosting.Company</p>
			<p><strong>مکان : </strong>@jobPosting.Location</p>

			@if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Employer))
			{
				<div id="jobPosting-@jobPosting.Id">
					<button class="btn btn-danger" onclick="deleteJobPosting(@jobPosting.Id)">حذف</button>
				</div>
			}

		</div>
	}

</div>

@section Scripts {
	<script>
		function deleteJobPosting(id){

			if(confirm("آیا از حذف مطمعن هستید؟")){

				$.ajax({
					url : "@Url.Action("Delete", "JobPostings")/" + id,
					type : "delete" ,
					success : function (result) {
						$("#jobPosting-" + id ).remove();
					},
					error : function (err){
						alert("خطایی رخ داده است");
					}
				});

			}
		}
	</script>
}